### PR TITLE
Add pre-commit config

### PR DESCRIPTION
**Pull request by paulineribeyre**
please review .secrets.baseline

### CODE REVIEW

**Review by mfshao — DISMISSED** [review]

**Review by mfshao — COMMENTED** [review]
we need to exclude those test data from `trailing-whitespace`, otherwsie the tests will fail (there are intended whitespaces in the test data)

**Comment by paulineribeyre** [comment]
oh thanks for investigating, i'll fix it manually

**Comment by mfshao** [comment]
> oh thanks for investigating, i'll fix it manually

or maybe just archieve this repo and forget about it 😄

**Comment by paulineribeyre** [comment]
archiving

**Pull request closed without merging**
